sudo: required

services:
  - docker

language: node_js
node_js:
  - "8"

env:
  - TRUFFLE_DEVELOP_HOST=truffle TRUFFLE_DEVELOP_PORT=9545'

before_install:
  - pwd
  - docker-compose --version
  - docker-compose up -d
  - sleep 4
  - docker-compose ps

install:
  - docker-compose exec truffle npm install
  - docker-compose exec truffle truffle migrate

script:
  - docker-compose exec truffle truffle test
