sudo: required

services:
  - docker

language: node_js
node_js:
  - "8"

env:
  - TRUFFLE_DEVELOP_HOST=truffle TRUFFLE_DEVELOP_PORT=9545 TRAVIS_WORKER_DOCKER_BINDS='${TRAVIS_BUILD_DIR}:/app'

before_install:
  - pwd
  - docker-compose --version
  - docker-compose up -d
  - sleep 4
  - docker-compose ps
  - docker-compose exec truffle truffle migrate
  - docker-compose exec truffle truffle test
