version: '3'
services:
  truffle:
    build:
      context: .
    image: market-protocol:1.0.0
    command: truffle develop
    volumes:
      - ./:/app
    tty: true
    stdin_open: true

  eth-bridge:
    image: perfectmak/ethereum-bridge:0.5.5
    command: -H ${TRUFFLE_DEVELOP_HOST}:${TRUFFLE_DEVELOP_PORT} -a 9 --dev
    depends_on:
      - truffle
    links:
      - truffle

  truffle-coverage:
    build:
      context: .
    image: market-protocol:1.0.0
    command: scripts/coverage_setup.sh
    volumes:
      - ./:/app
    tty: true
    stdin_open: true

  eth-bridge-coverage:
    image: cryptomental/ethereum-bridge-coverage:0.5.5
    command: -H ${TRUFFLE_COVERAGE_HOST}:${TRUFFLE_COVERAGE_PORT} -a 9 --dev
    depends_on:
      - truffle-coverage
    links:
      - truffle-coverage
